name: Build LINUX AMD64 TOR Binary

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build-linux-amd64-tor:
    runs-on: ubuntu-latest
    env:
      TAGS: "with_gvisor,with_quic,with_wireguard,with_dhcp,with_ech,with_utls,with_reality_server,with_embedded_tor,staticOpenssl,staticZlib,staticLibevent"

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.x'
        check-latest: true

    - name: Install dependencies
      run: |
        sudo apt-get install -y gcc sed libevent-dev libevent-openssl-2.1-7 openssl libssl-dev zlib1g-dev autoconf file automake
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig:$PKG_CONFIG_PATH

    - name: Create release folder
      run: sudo mkdir release

    - name: Build Current binary
      run: |
        CURRENT_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases | grep 'tag_name' | grep -v 'alpha' | grep -v 'rc' | head -n 1 | awk -F\" '{print $4}')
        sudo env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go install -ldflags "-X github.com/sagernet/sing-box/constant.Version=$CURRENT_VERSION" -v -tags ${{ env.TAGS }} github.com/sagernet/sing-box/cmd/sing-box@$CURRENT_VERSION
        sudo mv -f /root/go/bin/sing-box ./release/sing-box

    - name: Push Files
      run: |
        sudo chown -R $USER:$USER ./release
        sudo chmod -R 777 ./release
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "github-actions[bot]"
        sudo git add ./release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./sing-box*
        tag: ${{ github.ref }}
        file_glob: true
